# Generated by Django 2.0.13 on 2021-09-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
